### ISSUE TITLE
15_pointlight example doesn't build with gcc 12.1.0

### ISSUE THREAD

**Issue by kannoneer** [HailToDodongo/tiny3d#25]
```
> make clean && make -B
    [CC] main.c
main.c:37:1: error: 'noreturn' attribute ignored [-Werror=attributes]
   37 | [[noreturn]]
      | ^
cc1: all warnings being treated as errors
make: *** [/home/user/.local/n64_toolchain_gfx/include/n64.mk:177: build/main.o] Error 1
```

```
$N64_INST/bin/mips64-elf-gcc --version
mips64-elf-gcc (GCC) 12.1.0
Copyright (C) 2022 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Could be some configuration issue also on my end.

tiny3d commit 99dfc05410600f2bbcff9e4f68b8343344483f53
libdragon commit e36e91ea4ede4f70472bbf0086689ff5f4cf4aa5

**Edit:** I think this means I need to update my libdragon toolchain :)

**Comment by kannoneer** [comment]
Yeah works after updating the toolchain so gcc is 14.2.0. Closing.
